### ISSUE TITLE
Score & Turn control button

### ISSUE THREAD

**Issue by ohwowoAo** [team-5jo/The-Game-of-Pig#3]
## 설명

1. Score : 획득한 누적 점수를 숫자와 score bar를 통해 구현
2. Roll button : Roll button을 클릭하면 주사위를 돌려 랜덤으로 숫자 뽑기 구현
3. Hold click : turn을 멈추고 컴퓨터에게 순서를 넘김

## Tasks

- [x] Score : 획득한 점수를 보여준다.
- [x] Roll click : turn을 유지한다.
- [x] Hold click : turn을 멈춘다.
